config/routes.rb
Uploadist::Application.routes.draw do
  resources :albums do 
    resources :photos
  end

  resources :album_photos

  

  resources :ratings

  resources :users, :albums, :photos
  root to: 'users#home'

  get 'signup', to: 'users#new', as: 'signup'


  # OmniAuth stuff 
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
end

app/models/album_photo.rb
class AlbumPhoto < ActiveRecord::Base
  belongs_to :photo
  belongs_to :album
  belongs_to :user
end

app/controllers/album_photos_controller.rb
class AlbumPhotosController < ApplicationController
  before_action :set_album_photo, only: [:show, :edit, :update, :destroy]

  # GET /album_photos
  # GET /album_photos.json
  def index
    @album_photos = AlbumPhoto.all
  end

  # GET /album_photos/1
  # GET /album_photos/1.json
  def show
  end

  # GET /album_photos/new
  def new
    @album_photo = AlbumPhoto.new
  end

  # GET /album_photos/1/edit
  def edit
  end

  # POST /album_photos
  # POST /album_photos.json
  def create
    @album_photo = AlbumPhoto.new(album_photo_params)

    respond_to do |format|
      if @album_photo.save
        format.html { redirect_to @album_photo, notice: 'Album photo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @album_photo }
      else
        format.html { render action: 'new' }
        format.json { render json: @album_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /album_photos/1
  # PATCH/PUT /album_photos/1.json
  def update
    respond_to do |format|
      if @album_photo.update(album_photo_params)
        format.html { redirect_to @album_photo, notice: 'Album photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @album_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /album_photos/1
  # DELETE /album_photos/1.json
  def destroy
    @album_photo.destroy
    respond_to do |format|
      format.html { redirect_to album_photos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album_photo
      @album_photo = AlbumPhoto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_photo_params
      params.require(:album_photo).permit(:photo_id, :album_id, :user_id)
    end
end

app/helpers/album_photos_helper.rb
module AlbumPhotosHelper
end

app/views/album_photos/_form.html.erb
<%= form_for(@album_photo) do |f| %>
  <% if @album_photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album_photo.errors.count, "error") %> prohibited this album_photo from being saved:</h2>

      <ul>
      <% @album_photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :photo_id %><br>
    <%= f.text_field :photo_id %>
  </div>
  <div class="field">
    <%= f.label :album_id %><br>
    <%= f.text_field :album_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/album_photos/edit.html.erb
<h1>Editing album_photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @album_photo %> |
<%= link_to 'Back', album_photos_path %>

app/views/album_photos/index.html.erb
<h1>Listing album_photos</h1>

<table>
  <thead>
    <tr>
      <th>Photo</th>
      <th>Album</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @album_photos.each do |album_photo| %>
      <tr>
        <td><%= album_photo.photo %></td>
        <td><%= album_photo.album %></td>
        <td><%= album_photo.user %></td>
        <td><%= link_to 'Show', album_photo %></td>
        <td><%= link_to 'Edit', edit_album_photo_path(album_photo) %></td>
        <td><%= link_to 'Destroy', album_photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album photo', new_album_photo_path %>

app/views/album_photos/new.html.erb
<h1>New album_photo</h1>

<%= render 'form' %>

<%= link_to 'Back', album_photos_path %>

app/views/album_photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Photo:</strong>
  <%= @album_photo.photo %>
</p>

<p>
  <strong>Album:</strong>
  <%= @album_photo.album %>
</p>

<p>
  <strong>User:</strong>
  <%= @album_photo.user %>
</p>

<%= link_to 'Edit', edit_album_photo_path(@album_photo) %> |
<%= link_to 'Back', album_photos_path %>