config/routes.rb
Uploadist::Application.routes.draw do
  resources :albums do 
    resources :photos
  end

  resources :album_photos

  

  resources :ratings

  resources :users, :albums, :photos
  root to: 'users#home'

  get 'signup', to: 'users#new', as: 'signup'


  # OmniAuth stuff 
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
end

app/models/album.rb
class Album < ActiveRecord::Base
  default_scope order('created_at DESC')
 
 # # Environment-specific direct upload url verifier screens for malicious posted upload locations.
 #  DIRECT_UPLOAD_URL_FORMAT = %r{\Ahttps:\/\/s3-us-west-2\.amazonaws\.com\/uploadist\/(?<filepath>uploads\/.+\/(?<filename>.+))\z}.freeze
 # # https://s3-us-west-2.amazonaws.com/uploadist/uploads%2F1386814274254-16hda061d84r6bt9-86404601a344c663ad17c4eda70f4403%2FNick%2BGrosvenor%2BKatie%2BLaBarge%2BLCDQ%2BLa%2BCienega%2BRigZnefelABl.jpg
  belongs_to :user
  has_many :album_photos
  has_many :photos, through: :album_photos, source: :photo
 #  # validates :direct_upload_url, presence: true, format: { with: DIRECT_UPLOAD_URL_FORMAT }
    
 #  before_create :set_upload_attributes
 #  after_create :queue_processing
  
  
 #  # Store an unescaped version of the escaped URL that Amazon returns from direct upload.
 #  def direct_upload_url=(escaped_url)
 #    write_attribute(:direct_upload_url, (CGI.unescape(escaped_url) rescue nil))
 #  end
  
 #  # Determines if file requires post-processing (image resizing, etc)
 #  def post_process_required?
 #    %r{^(image|(x-)?application)/(bmp|gif|jpeg|jpg|pjpeg|png|x-png)$}.match(upload_content_type).present?
 #  end
  
 #  # Final upload processing step
 #  def self.transfer_and_cleanup(id)
 #    album = Album.find(id)
 #    direct_upload_url_data = DIRECT_UPLOAD_URL_FORMAT.match(album.direct_upload_url)
 #    s3 = AWS::S3.new
    
 #    if album.post_process_required?
 #      album.upload = URI.parse(URI.escape(album.direct_upload_url))
 #    else
 #      paperclip_file_path = "albums/uploads/#{id}/original/#{direct_upload_url_data[:filename]}"
 #      s3.buckets[Rails.configuration.aws[:bucket]].objects[paperclip_file_path].copy_from(direct_upload_url_data[:filepath])
 #    end
 
 #    album.processed = true
 #    album.save
    
 #    s3.buckets[Rails.configuration.aws[:bucket]].objects[direct_upload_url_data[:filepath]].delete
 #  end
      
 #  private
  
 #  # Set attachment attributes from the direct upload
 #  # @note Retry logic handles S3 "eventual consistency" lag.
 #  def set_upload_attributes
 #    tries ||= 5
 #    direct_upload_url_data = DIRECT_UPLOAD_URL_FORMAT.match(direct_upload_url)
 #    s3 = AWS::S3.new
 #    direct_upload_head = s3.buckets[Rails.configuration.aws[:bucket]].objects[direct_upload_url_data[:filepath]].head
 
 #    self.upload_file_name     = direct_upload_url_data[:filename]
 #    self.upload_file_size     = direct_upload_head.content_length
 #    self.upload_content_type  = direct_upload_head.content_type
 #    self.upload_updated_at    = direct_upload_head.last_modified

 #  rescue AWS::S3::Errors::NoSuchKey => e
 #    tries -= 1
 #    if tries > 0
 #      sleep(3)
 #      retry
 #    else
 #      false
 #    end
 #  end
  
 #  # Queue file processing
 #  def queue_processing
 #    Album.delay.transfer_and_cleanup(id)
 #  end
 
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  
  # @http_method XHR POST
  # @url /documents
  def create
  #   if current_user
  # @album = Album.create!(album_params)
  #   end
        if current_user
      @album = current_user.albums.create!(album_params)

      @album.photos.create(direct_upload_url: @album.direct_upload_url, rating_amount: 0)
      redirect_to :back
        else
        redirect_to root_url 
        
  
        end
  end


  def show
  @album = Album.find(params[:id])
  @photo = Photo.new


  end   


private

  def album_params
        params.require(:album).permit(:direct_upload_url, :name)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/create.html.erb
Dude here's your thinger:

<%= raw @album.inspect %>

app/views/albums/create.js.erb
<% if @album.persisted? %>
 
<% else %>
  $('#upload_<%=params[:unique_id]%> div.progress').removeClass('active progress-striped').addClass('progress-danger');
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<div class="container">
  <div class="file-upload main-container">
    <h3 id="drag-here">Drag all photos here</h3>
      <%= s3_uploader_form callback_url: albums_url, id: "s3-uploader", callback_param: "album[direct_upload_url]", expiration: 24.hours.from_now.utc.iso8601, max_file_size: 5.megabytes do %>
      <%= hidden_field_tag  "Content-type", "" %>
      <%= file_field_tag :file, multiple: true %>
    <% end %>
    <div id="uploads_container"></div>
    <script id="template-upload" type="text/x-tmpl">
    <div id="upload_{%=o.unique_id%}" class="upload">
    <div id="upload-image"></div>
      <div class="progress progress-striped active"><div class="bar" style="width: 0%"></div></div>
    </div>
    </script>
  </div>
</div>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<div class="show_header">
     <div class="create_photos">
      <%= form_for [@album, @photo] do |a|%>
            <%= a.text_field :direct_upload_url, placeholder: "P H O T O" %>
            <%= a.submit %>
      <% end %>
     </div>

     
       <a href="/"><div class="hot_photos">HOT</div></a>
        <a href="/users"><div class="new_photos">NEW</div></a>
        
    </div>   
</div>
  

<div class="album_show_container">

      
    
      <% @album.photos.order("rating_amount DESC").each do |p| %>
  <div class="photo_wrapper">
    <div class="rating_wrapper">
        <div id="U<%= p.id %>" class="upvote"> 
            <div class="glyphicon glyphicon-chevron-up"></div> 
        </div>
              <div class="rating_number"><div id="pRating<%= p.id %>"><%= p.rating_amount %></div>
              </div>
              <!-- How many ratings: <%#= p.ratings.count %> -->
        <div id="D<%= p.id %>" class="downvote">
            <div class="glyphicon glyphicon-chevron-down"></div>
        </div>
    </div>
            <img id="img<%= p.id %>" src="<%= p.direct_upload_url %>"
                style="opacity:<%= 1.0 - (0.25 * (-p.rating_amount)) %>;"
             />
  </div>        
      <% end %>

      <script>
        $(".upvote").on("click", function(xyz){
          $.ajax({
      type: "POST",
      url: "/ratings",
      data: {rating:{"photo_id": this.id.substring(1,999),
      "is_good":true}},
      success:
             function(data){
              $("#pRating"+data.id).html(data.rating);
              $("#img"+data.id).css("opacity",1.0 - (0.25 * (-data.rating)));
          }
        });
      });

        $(".downvote").on("click", function(xyz){
          $.ajax({
      type: "POST",
      url: "/ratings",
      data: {rating:{"photo_id": this.id.substring(1,999),
      "is_good":false}},
      success:
             function(data){
              $("#pRating"+data.id).html(data.rating);
              $("#img"+data.id).css("opacity",1.0 - (0.25 * (-data.rating)));
          }
        });
      });
      </script>
      
</div>      